### ISSUE TITLE
MBED .hex file doesn't run

### ISSUE THREAD

**Issue by DuyTrandeLion** [VNGIoTLab/vbluno#1]
Hello,

I followed your instruction on https://vngiotlab.github.io/vbluno/vi/mydoc_getstart_mbedonline_vi.html using the mbed online compiler and VBLUno51. The program compiled without any error but when I copied the .hex file to the board, nothing happened. I programmed the board with Arduino IDE and it worked fine. Do you have any ways to figure it out? Thank you.

**Comment by iotmember** [comment]
@DuyTrandeLion  I helped you fix this issue on Facebook Messenger. Many thanks for your report.
